### ISSUE TITLE
Trial period zeroed out.

### ISSUE THREAD

**Issue by Scrotalitch** [keshavbhatt/ultimate-media-downloader-linux#23]
Hi there... I am two days in on the trial period and although I love this app, I had trouble with bitchute downloads (as seen in issue number 22, below) In the absense of any immediate help I continued to read and saw that you suggested Cookie Capture in issue number 21. So I added this extension which caused more problems and I couldn't download ANYTHING which I could not repair.

I then had to uninstall the entire thing and reinstall it, thus zeroing out my trial period (understandably)

Do I have to pay for a month now to continue y trial or cn we please sort something out?

-Pat

Ps. Apart from these minor issues and as previously stated, I love this app and have every intention of purchasing it at the end of the trial period; I just wasn't expecting it to be less three three days.

Thank you for time and understanding...

**Comment by keshavbhatt** [comment]
Hi Pat,

Thank you for reaching out and for your kind words about the app. I apologize for the issues you've encountered. The trial period is typically 15 days, but given your situation, I’m happy to offer you an additional month of free evaluation. For that I will need your account ID. Please reach me out via email since it is not good idea to pass your account ID here. 

Please let me know if there are any other issues or questions you have. I am here to help!

Best regards

**Comment by Scrotalitch** [comment]
Email sent to 98378sub@gmail.com.
Many thanks
-Pat
